### ISSUE TITLE
Pie Charts

### ISSUE THREAD

**Issue by juanespj** [plotly/plotly.rs#130]
I have been working on some pie chart Diagrams, I was wondering if you have started any work on this, I will be happy to contribute

**Comment by mfreeborn** [comment]
Nothing specific for pie charts - wil happily review PRs :)

**Comment by andrei-ng** [comment]
@juanespj, would you be interested to submit your work as a PR?

**Comment by CriticalTea** [comment]
Any updates here? Loving the mappings so for, only thing missing are pie charts. Unfortunately I'm a total beginner (started 2 days ago), so I can't really contribute a lot...

**Comment by andrei-ng** [comment]
@CriticalTea , unfortunately so far not. I will try to find some time to do it in the next few weeks.

**Comment by andrei-ng** [comment]
@CriticalTea , the basics have been added in https://github.com/plotly/plotly.rs/pull/265

**Comment by CriticalTea** [comment]
@andrei-ng Great to hear! I'll check it out. Thanks a lot! :)
