### ISSUE TITLE
Requesting patterns for bar charts, and histograms.

### ISSUE THREAD

**Issue by moinmoti** [plotly/plotly.rs#145]
I could not find any documentation for adding [patterns](https://plotly.com/python/pattern-hatching-texture/) to bar charts or histograms, so I understand they are not supported as of now. Are there any plans to support patterns? And if they are indeed already supported, can someone please link the relevant doc page/example?

**Comment by Nick-Pearson** [comment]
This would be a very useful feature for generating charts that are accessible to the colour blind
It could be implemented by exposing this pattern fill feature from plotly.js https://github.com/plotly/plotly.js/pull/5520

**Comment by Nick-Pearson** [comment]
I am happy to contribute a PR for the pattern fill feature

**Comment by andrei-ng** [comment]
> I am happy to contribute a PR for the pattern fill feature

That would be awesome!
