### ISSUE TITLE
plot.show() does not work on Linux snap Firefox 

### ISSUE THREAD

**Issue by MarkSwanson** [plotly/plotly.rs#170]
*snap* Firefox has its own /tmp directory now. *snap* Firefox no longer sees the real /tmp directory - so it can't find the plotly generated HTML file.
Firefox 119.0
Ubuntu 22.04

Possible solution: plotly already provides  plot.write_html(filename)  -  so just provide a plot.show(filename) ?

Thanks!

**Comment by andrei-ng** [comment]
@MarkSwanson, yes, you are correct. With snap, even most (all) of the examples won't work. 

I will look into it.

**Comment by andrei-ng** [comment]
@MarkSwanson , I added a straightforwad implementation in #217. If this what you had in mind? 
I actually used it as I got bit by snap as well :)

**Comment by andrei-ng** [comment]
I am going to merge it.
