### ISSUE TITLE
Plotly.rs Book link is broken

### ISSUE THREAD

**Issue by adwinwhite** [plotly/plotly.rs#200]
In README, there is a broken interactive [Plotly.rs Book](https://igiagkiozis.github.io/plotly/content/getting_started.html) link.
I guess it's generated from `docs/book` via mdbook.
How to bring it alive again?

**Comment by andrei-ng** [comment]
Thanks for reporting it @adwinwhite ! The project has been moved to a new space, probably the mbook generation for broken. Will have a look at it.

**Comment by andrei-ng** [comment]
@adwinwhite the link in the README in the `main` branch is currently pointing at the incorrect page. Once PR https://github.com/plotly/plotly.rs/pull/193 is merged, the README href will be fixed.

If you need to access the book, you can find it here: https://plotly.github.io/plotly.rs/

**Comment by andrei-ng** [comment]
Fixed in #193
