### ISSUE TITLE
clippy::manual_unwrap_or_default triggers on macro generated code from darling crate

### ISSUE THREAD

**Issue by andrei-ng** [plotly/plotly.rs#210]
Temporarily, the CI has been fixed by adding ` -Aclippy::manual_unwrap_or_default` to all clippy jobs.

These should be removed from CI workflow file once the issue is fixed upstream. 
See: 
https://github.com/rust-lang/rust-clippy/issues/12643
https://github.com/TedDriggs/darling/issues/293

**Comment by TedDriggs** [comment]
The fix for this has moved to TedDriggs/darling#296
