### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by gwbres** [plotly/plotly.rs#213]
Hello, would it be possible to make the two newly available plots official ?

**Comment by andrei-ng** [comment]
It's coming soon. Stay tuned... :)

**Comment by wangjiawen2013** [comment]
Looking forward to it!

**Comment by andrei-ng** [comment]
New version available: https://crates.io/crates/plotly .
Updated the book as well. :partying_face:  Let me know if you spot issues.

**Comment by gwbres** [comment]
Thank you for all your work @andrei-ng,

I will come back to you, I developped a couple of widgets that might be interesting to other people
