### ISSUE TITLE
Titles in all examples

### ISSUE THREAD

**Issue by wangjiawen2013** [plotly/plotly.rs#223]
Hi,
I cannot run some of the example code in plotly.rs.book. I find all the `.title(Title::new("balabala")` should be adjusted to `.title(Title::with_text("balabala")` in order to run the examples successfully.
Besides, `.side(Side::Right),` must be adjusted to `.side(AxisSide::Right),` too.

**Comment by andrei-ng** [comment]
Hi @wangjiawen2013 . Good catch!
Indeed, latest release has changed the API to allow passing all sorts of strings to title(s). We've missed the examples in the book.
