### ISSUE TITLE
Scatter trace

### ISSUE THREAD

**Issue by wangjiawen2013** [plotly/plotly.rs#224]
Hi,
All the scatter plot in the examples need the trace trait, which is not used now. So the the following error will occur, and the error message is meaningless:
![image](https://github.com/user-attachments/assets/5dff7f54-4683-4b3c-ba67-7c3da5b9d496)

We need `use plotly::{Plot, Scatter, Trace}` instead of `use plotly::{Plot, Scatter}`. Because other plots such as heatmap, contour don't need the `Trace` trait, how to fix it ?

**Comment by andrei-ng** [comment]
Thanks for the report, I will have a look and come back to you.

**Comment by andrei-ng** [comment]
I can't reproduce on `main`. I can compile and run all the `Scatter3D` examples in `examples/3d_charts/src/main.rs` without any errors and warnings. 

Also, please provide the example as inline code and the error as text and not as a screenshot. It makes difficult to search the codebase for key words.
