### ISSUE TITLE
Add function to export image (with Kaleido) as a b64 string 

### ISSUE THREAD

**Issue by mchant** [plotly/plotly.rs#247]
Would it be useful if I create a PR for a to_b64 function? It's pretty much a copy of the write_image function, but returns a b64 string rather than write to a file.

**Comment by andrei-ng** [comment]
Isn't [`to_html`](https://github.com/plotly/plotly.rs/blob/8580c87785f5fce0a89f8925161960c185514a4c/plotly/src/plot.rs#L337)  or [`to_inline_html`](https://github.com/plotly/plotly.rs/blob/8580c87785f5fce0a89f8925161960c185514a4c/plotly/src/plot.rs#L354) sufficient for this use-case?

**Comment by mchant** [comment]
Thanks for the reply, @andrei-ng. Those functions return html that makes a call to plotly. If someone just wants data for a picture, they can use this tag (<img src="data:image/jpeg;base64,{b64_string_here}">) and pass in the string. This also returns a fairly consistent data length no matter how much data is used in the plot. In an HTTP API environment, this makes a more predictable load time because the data returned is not dependent on the length of x and y.

**Comment by andrei-ng** [comment]
Hi @mchant. Thanks for the clarification. Yes, please submit a PR and I will merge it in. If you need to use an external crate to achieve this, I think it is better to put it behind a feature flag.

**Comment by mchant** [comment]
Hi, @andrei-ng , it's in PR https://github.com/plotly/plotly.rs/pull/251

**Comment by andrei-ng** [comment]
closed by #251
