### ISSUE TITLE
Book recipes do not render graphs

### ISSUE THREAD

**Issue by Nick-Pearson** [plotly/plotly.rs#248]
The graphs in the book recipes are not rendering due to the inline html being generated with an old version of plotly.js
They fail with this error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'select')
    at scatter_plots.html:347:31
```
e.g. [Scatter Plots](https://plotly.github.io/plotly.rs/content/recipes/basic_charts/scatter_plots.html)

Additionally the code in the book recipes can drift from the code in the `examples` directory.

MD Book has a feature which allows inserting code directly from other files https://rust-lang.github.io/mdBook/format/mdbook.html#including-portions-of-a-file
The book could include rust source code and rendered html fragments directly from the examples. That way it can be ensured the recipes compile and can produce a rendered graph

I am happy to submit a PR for this

**Comment by andrei-ng** [comment]
That would be awesome if you are willing to do that!

**Comment by andrei-ng** [comment]
@Nick-Pearson , your contribution is now released as part of the official book: https://plotly.github.io/plotly.rs/content/recipes/basic_charts/line_charts.html

Thank you! @Nick-Pearson
