### ISSUE TITLE
Release new versions

### ISSUE THREAD

**Issue by LafeWessel** [plotly/plotly.rs#252]
I see in the Changelog that there are two versions, 0.10.1 and 0.11.0, that have not yet been published to crates.io. I would like to take advantage of some changes made in those versions. Could whomever is maintaining this crate publish the versions for others to use?

**Comment by andrei-ng** [comment]
Thanks for reporting this. I actually didn't realise that. Will release the missing versions asap .

**Comment by andrei-ng** [comment]
@LafeWessel , just released the latest version: https://crates.io/crates/plotly
